### ISSUE TITLE
No such file or directory, mount failed

### ISSUE THREAD

**Issue by farmergreg** [calmh/smartos-platform-upgrade#19]
This script has been working very well for me for a long time, but suddenly, it's not working on both servers that I manage here's some example output:

I'm running 20171026T003127Z on both servers.

    Downloading latest platform (platform-20171109T032417Z.tgz)... OK
    Verifying checksum... OK
    Extracting latest platform... OK
    Marking release version... OK
    Checking current boot device... detected mount: No such file or directory, mount failed

**Comment by calmh** [comment]
Yeah, 20171026 release changed the way disks are presented. This was solved in #18, upgrade the script and you should be fine.

**Comment by farmergreg** [comment]
great, thanks!!
