### ISSUE TITLE
Checking current boot device... detected mount: No such file or directory , mount failed

### ISSUE THREAD

**Issue by farmergreg** [calmh/smartos-platform-upgrade#20]
One of my machines is still not working with the latest release. Here's what diskinfo shows (it should be finding the SanDisk Curzer Orbit usb stick):

> [root@smartos ~]# diskinfo -pH
ATA     c1d0    -       -       2000371580928   no      no
ATA     c2d0    -       -       2000371580928   no      no
SCSI    c3t0d0  SanDisk Cruzer Orbit    32015679488     no      no

I'm not sure why SmartOS is marking is as non removable, but i think that's why it's broken for this script.

**Comment by calmh** [comment]
That disk has removable=no which means platform-upgrade will not consider it. This is as designed. However It’s arguable that this is a bug in diskinfo or SmartOS to cause the change. In the meantime,

  platform-upgrade /dev/dsk/c3t0d0p1
