### ISSUE TITLE
$header fails for 20190605T231205Z

### ISSUE THREAD

**Issue by rolinux** [calmh/smartos-platform-upgrade#31]
The version 20190605T231205Z of the images has a `20190606` header instead of `20190605` as the script expects.
Extracting the $header from $version fails for this and the solution is to download the [latest spec file](https://us-east.manta.joyent.com/Joyent_Dev/public/SmartOS/20190605T231205Z) and regex the header from it.

PR soon

**Comment by calmh** [comment]
Ugh. Thanks for hacking on it.
