### ISSUE TITLE
Script should verify which version is currently used

### ISSUE THREAD

**Issue by foxycode** [calmh/smartos-platform-upgrade#9]
Script should verify (maybe by `uname -v`) which version of platform is currently used and exit if latest platform is same as current.

**Comment by bahamas10** [comment]
i've created 2 PR's implementing this, @calmh can choose which one makes the most sense.

- https://github.com/calmh/smartos-platform-upgrade/pull/11 - installer will exit if the latest version is already installed, and can be overridden with `-f` (perfect for non-interactive use)
- https://github.com/calmh/smartos-platform-upgrade/pull/10 - installer will prompt user if the platform is already at the latest, good for interactive use but not great for scripting

perhaps both can be merged into one by determining if the script is being run interactively (`[[ -t 1 ]]` or something)
